---
version: '2.1'

volumes:
  etcd:

services:
  aperture:
    image: lightninglabs/aperture:v0.1.18-beta
    network_mode: host
    volumes:
      - ./aperture/aperture.yaml:/root/.aperture/aperture.yaml
      - ./aperture/static:/root/.aperture/static
      - ./aperture/lnd:/root/.lnd
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: '2'
    depends_on:
      - api

  api:
    build:
      context: ./api
    image: bloxseer:v0.1.0-alpha
    environment:
      - FLASK_APP=/app/api.py
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0"]
    ports:
      - "5000:5000"
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: '2'

  bitcoin-exporter:
    image: jvstein/bitcoin-prometheus-exporter:v0.7.0
    environment:
      - LOG_LEVEL=DEBUG
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER:-bitcoin}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD:-bitcoin}
      - BITCOIN_RPC_HOST=${BITCOIN_RPC_HOST:-localhost}
      - BITCOIN_RPC_PORT=${BITCOIN_RPC_PORT:-8332}
    ports:
      - "9332:9332"

  etcd:
    image: bitnami/etcd:3.5.3
    restart: unless-stopped
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_AUTO_COMPACTION_MODE=revision
    volumes:
      - etcd:/bitnami/etcd
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: '2'

  prometheus:
    image: docker.io/prom/prometheus:v2.35.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:z
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    ports:
      - "9090:9090"
